# Alpine Linux with OpenJDK JRE
FROM openjdk:8-jre-alpine
# copy fat JAR
COPY target/phonebridge-admin-0.0.1-SNAPSHOT.jar /phonebridge-admin.jar
# runs application
CMD ["/usr/bin/java", "-jar","/phonebridge-admin.jar"]