# Alpine Linux with OpenJDK JRE
FROM openjdk:8-jre-alpine
# copy fat JAR
COPY target/phonebridge-config-server-0.0.1-SNAPSHOT.jar /phonebridge-config-server.jar
# runs application
CMD ["/usr/bin/java", "-jar","/phonebridge-config-server.jar"]