# Alpine Linux with OpenJDK JRE
FROM openjdk:8-jre-alpine
# copy fat WAR
COPY target/portalservice-0.0.1-SNAPSHOT.jar /portalservice.jar
# runs application
CMD ["/usr/bin/java", "-jar", "-Dspring.profiles.active=default", "-Dmongo.host=mongod-0.mongodb-service", "-Dmongo.port=27017", "-Dmongo.dbname=phonebridgedb","-Deureka.host=eureka-0.eureka:8761","/portalservice.jar"]