# Alpine Linux with OpenJDK JRE
FROM openjdk:8-jre-alpine
# copy fat JAR
COPY target/phonebridge-discovery-0.0.1-SNAPSHOT.jar /phonebridge-discovery.jar
# runs application
CMD ["/usr/bin/java", "-jar","/phonebridge-discovery.jar"]