# Alpine Linux with OpenJDK JRE
FROM openjdk:8-jre-alpine
# copy fat JAR
COPY target/phonebridge-authserver-0.0.1-SNAPSHOT.jar /phonebridge-authserver.jar
# runs application
CMD ["/usr/bin/java", "-jar","/phonebridge-authserver.jar"]